server:
  port: 7070
spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/mydb
    url: jdbc:mysql://127.0.0.1:3306/steadydb
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: TRUE
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
#  jooq:
#    sql-dialect: mysql